### ISSUE TITLE
Readme error related to linq reference

### ISSUE THREAD

**Issue by Sqvlen** [Bardin08/dotnet-roadmap#7]
If I try to follow a linq.md link in the README's table, I get a ```404``` result (page not found):
![image](https://github.com/Bardin08/dotnet-roadmap/assets/65315887/cafc9d33-f956-4887-858a-074ff83a4c99)

Because the link should refer to LINQ.md, not linq.md:
```/Practice/linq.md → /Practice/LINQ.md```

**Comment by Bardin08** [comment]
Thanks @Sqvlen! Fixed at #8
